//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 党建信息管理系统LS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("党建信息管理系统LS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _014 {
            get {
                object obj = ResourceManager.GetObject("014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _015 {
            get {
                object obj = ResourceManager.GetObject("015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _023 {
            get {
                object obj = ResourceManager.GetObject("023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _039 {
            get {
                object obj = ResourceManager.GetObject("039", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _054 {
            get {
                object obj = ResourceManager.GetObject("054", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _059 {
            get {
                object obj = ResourceManager.GetObject("059", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _063 {
            get {
                object obj = ResourceManager.GetObject("063", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _101 {
            get {
                object obj = ResourceManager.GetObject("101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1011 {
            get {
                object obj = ResourceManager.GetObject("1011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _102 {
            get {
                object obj = ResourceManager.GetObject("102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _103 {
            get {
                object obj = ResourceManager.GetObject("103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _104 {
            get {
                object obj = ResourceManager.GetObject("104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _105 {
            get {
                object obj = ResourceManager.GetObject("105", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _106 {
            get {
                object obj = ResourceManager.GetObject("106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _107 {
            get {
                object obj = ResourceManager.GetObject("107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _108 {
            get {
                object obj = ResourceManager.GetObject("108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _109 {
            get {
                object obj = ResourceManager.GetObject("109", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _110 {
            get {
                object obj = ResourceManager.GetObject("110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _111 {
            get {
                object obj = ResourceManager.GetObject("111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _112 {
            get {
                object obj = ResourceManager.GetObject("112", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _113 {
            get {
                object obj = ResourceManager.GetObject("113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _115 {
            get {
                object obj = ResourceManager.GetObject("115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _params {
            get {
                object obj = ResourceManager.GetObject("params", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ae5851d869670ad2_a28508a782f79c20_db245482de7ca04ec8e26863bab5d7e1 {
            get {
                object obj = ResourceManager.GetObject("ae5851d869670ad2-a28508a782f79c20-db245482de7ca04ec8e26863bab5d7e1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Bookmark {
            get {
                object obj = ResourceManager.GetObject("Bookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bulb {
            get {
                object obj = ResourceManager.GetObject("bulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bulb1 {
            get {
                object obj = ResourceManager.GetObject("bulb1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap calculator {
            get {
                object obj = ResourceManager.GetObject("calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap calendar1 {
            get {
                object obj = ResourceManager.GetObject("calendar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap calendar2 {
            get {
                object obj = ResourceManager.GetObject("calendar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap calendar3 {
            get {
                object obj = ResourceManager.GetObject("calendar3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap calendar4 {
            get {
                object obj = ResourceManager.GetObject("calendar4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap clip {
            get {
                object obj = ResourceManager.GetObject("clip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap files {
            get {
                object obj = ResourceManager.GetObject("files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Folder12 {
            get {
                object obj = ResourceManager.GetObject("Folder12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap megaphone {
            get {
                object obj = ResourceManager.GetObject("megaphone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pen {
            get {
                object obj = ResourceManager.GetObject("pen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap tag {
            get {
                object obj = ResourceManager.GetObject("tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 1)向党支部递交入党申请书
        ///　　申请人
        ///      ①本人自愿向党组织提出申请;②对于团支部推荐的入党对象和未提出入党申请，但政治素质好，有培养前途的人员，应吸收他们参加一些党的活动，使其逐步提高认识，自愿提出入党申请。
        ///　　↓
        ///　　2) 推优
        ///　　校团委推优的对象应在三好学生、文明大学生、优秀团员、优秀学生干部、文明教工和年度考核获得优秀等次者中筛选，具体条件、步骤、时间由校团委制定。
        ///　　↓
        ///　　3) 确定入党积极分子
        ///　　党支部对于已向党组织提出申请，符合党章规定的基本条件的同志，一般由党小组推荐，然后经党支部(不设支委会的由支部大会)讨论决定，方可列为入党积极分子，并确定2名党员为其培养联系人。
        ///　　↓
        ///　　4)填写《入党积极分子登记表》
        ///　　党支部对已确定的入党积极分子，党支部要为其填写《入党积极分子登记表》，表格由党支部(联系人)统一保管。
        ///　　↓
        ///　　5) 培养教育
        ///　　党支部
        ///      ① 组织入党积极分子参加学习小组;
        ///      ②组织他们上党课或参加党内有关活动;?
        ///      ③给他们分配一定的社会工作;
        ///      ④推荐其参加学校的业余党校培训 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 入党流程 {
            get {
                return ResourceManager.GetString("入党流程", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 党员发展流程之入党申请
        ///
        ///一、入党申请
        ///入党条件：
        ///1、年满十八岁的中国工人、农民、军人、知识分子和其他社会阶层的先进分子；
        ///2、承认党的纲领和章程；
        ///3、愿意参加党的一个组织并在其中积极工作；
        ///4、愿意执行党的决议；
        ///5、愿意按期交纳党费。
        ///方式：向工作、学习所在单位党组织提出入党申请；没有工作、学习单位或工作、学习单位未建立党组织的，向居住地党组织提出入党申请；流动人员还可以向单位所在地党组织或单位主管部门党组织、流动党员党组织提出入党申请。
        ///注意事项∶
        ///1、宗教信仰问题∶共产党员是唯物主义者和无神论者。因此，信仰宗教的人和有浓厚宗教感情的人不能入党。但要把在思想上能同宗教信仰划清界限，为了不脱离群众，在生活中尊重和随顺参加带有宗教色彩的民族风俗活动的人，同笃信宗教和有浓厚宗教感情的人区别开来；把拥护党的主张，积极为党工作，愿意服从党的纪律，但尚未完全摆脱宗教影响的人，同坚持有神论，怀疑党的路线、方针、政策的人区别开来。笃信宗教和有浓厚宗教感情的人同宗教实行彻底决裂，真正树立了辩证唯物主义和历史唯物主义世界观，经过组织考察，认为已经具备党员条件的，才能吸收入党。
        ///2、是否是团员及入 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 入党申请 {
            get {
                return ResourceManager.GetString("入党申请", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 党员发展流程之入党申请
        ///
        ///一、入党申请
        ///入党条件：
        ///1、年满十八岁的中国工人、农民、军人、知识分子和其他社会阶层的先进分子；
        ///2、承认党的纲领和章程；
        ///3、愿意参加党的一个组织并在其中积极工作；
        ///4、愿意执行党的决议；
        ///5、愿意按期交纳党费。
        ///方式：向工作、学习所在单位党组织提出入党申请；没有工作、学习单位或工作、学习单位未建立党组织的，向居住地党组织提出入党申请；流动人员还可以向单位所在地党组织或单位主管部门党组织、流动党员党组织提出入党申请。
        ///注意事项∶
        ///1、宗教信仰问题∶共产党员是唯物主义者和无神论者。因此，信仰宗教的人和有浓厚宗教感情的人不能入党。但要把在思想上能同宗教信仰划清界限，为了不脱离群众，在生活中尊重和随顺参加带有宗教色彩的民族风俗活动的人，同笃信宗教和有浓厚宗教感情的人区别开来；把拥护党的主张，积极为党工作，愿意服从党的纪律，但尚未完全摆脱宗教影响的人，同坚持有神论，怀疑党的路线、方针、政策的人区别开来。笃信宗教和有浓厚宗教感情的人同宗教实行彻底决裂，真正树立了辩证唯物主义和历史唯物主义世界观，经过组织考察，认为已经具备党员条件的，才能吸收入党。
        ///2、是否是团员及入 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 入党申请说明 {
            get {
                return ResourceManager.GetString("入党申请说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 党员应知应会基本知识
        ///1. 入党誓词：
        ///      我志愿加入中国共产党，拥护党的纲领，遵守党的章程，履行党员义务，执行党的决定，严守党的纪律，保守党的秘密，对党忠诚，积极工作，
        ///为共产主义奋斗终身，随时准备为党和人民牺牲一切，永不叛党。
        ///
        ///2. “五位一体”总体布局：
        ///    经济建设、政治建设、文化建设、社会建设、生态文明建设。
        ///
        ///3. “四个全面”战略布局：全面建成小康社会、全面深化改革、全面依法治国、全面从严治党。
        ///
        ///4. 五大发展理念：创新、协调、绿色、开放、共享。
        ///
        ///5. 四个自信：道路自信、理论自信、制度自信、文化自信。
        ///
        ///6. 四个意识：政治意识、大局意识、核心意识、看齐意识。
        ///
        ///7. 中国共产党人的初心和使命：为中国人民谋幸福，为中华民族谋复兴。
        ///
        ///8. 好干部“五条标准”：信念坚定、为民服务、勤政务实、敢于担当、清正廉洁。
        ///
        ///9. 两学一做：学党章党规、学系列讲话，做合格党员。
        ///
        ///10. 党员四个合格：政治合格、品德合格、执纪合格、发挥作用合格。
        ///
        ///11. 党面临的“四大危险”：精神懈怠危险、能力不足危险、脱离群众危险、消极腐败危险。
        ///
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 基本知识 {
            get {
                return ResourceManager.GetString("基本知识", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一、党小组向党支部推荐发展对象
        ///
        ///      党小组长以口头或书面形式向党支部提名推荐发展对象。
        ///
        ///二、党支部制定并上报发展计划
        ///
        ///      列入发展计划的对象必须是培养考察一年以上的，政历清楚，基本符合党员条件的入党积极分子，并须经支委会讨论通过。
        ///
        ///三、党委审定发展计划
        ///
        ///       计划审定后，下发至各党支部。
        ///
        ///四、党委集中培训发展对象
        ///
        ///       培训时间为5—7天（或不少于40个学时）。主要学习《党章》、《关于党内政治生活的若干准则》、《入党培训教材》等。未经过培训的，原则上不予发展。
        ///
        ///五、党小组提出发展意见并向支部推荐
        ///
        ///       对入党积极分子进行定期考察后，将本小组的考察意见形成文字材料上交党支部。
        ///
        ///六、党支部征求党内外群众意见
        ///
        ///       党支部将积极分子情况公示，并召开座谈会或个别征求意见，形成书面材料。
        ///
        ///七、党支部召开支委会确定发展对象
        ///
        ///       对经过一年以上培养考察的对象，通过基层座谈了解，民主测评，征求党小组意见后，召开拟定重点培养方案，订出发展计划，报送上级党委。
        ///
        ///八、党支部向党委报告
        ///
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 确定发展对象 {
            get {
                return ResourceManager.GetString("确定发展对象", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一、申请人向党支部递交入党申请书
        ///
        ///     团支部向党支部择优推荐入党对象。
        ///
        ///二、党支部确定培养人
        ///
        ///      党支部对申请人和团支部择优推荐的对象，要经常找其谈话，及时确定1—2名党员负责培养。
        ///
        ///三、党支部召开支委会，确定入党积极分子
        ///
        ///      由党小组提名，支委会讨论通过上报，党委组织部门汇总备案。
        ///
        ///四、党支部、党小组、培养人教育、培养、考察
        ///
        ///  方法：
        ///
        ///（1）党的基本知识、基本路线教育；
        ///
        ///（2）分配一定的工作任务；
        ///
        ///（3）经常谈心了解思想情况；
        ///
        ///（4）参加党内有关活动；
        ///
        ///（5）政审。
        ///
        ///五、党支部、党小组、培养人定期填写《积极分子考察登写实簿》
        ///
        ///      每季度由培养人填写，党小组、党支部签署意见。党支部每半年作一次写实性考察鉴定。
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string 积极分子 {
            get {
                return ResourceManager.GetString("积极分子", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 系统背景 {
            get {
                object obj = ResourceManager.GetObject("系统背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 一、党支部、党小组、介绍人继续对预备党员培养教育、考察
        ///
        ///方法：
        ///
        ///（1）、党的基本知识教育；
        ///
        ///（2）、分配一定的工作任务；
        ///
        ///（3）、听取党内外群众反映；
        ///
        ///（4）、预备党员定期汇报思想；
        ///
        ///（5）、介绍人定期向支部报告考察意见。
        ///
        ///二、预备党员到期提出转正申请
        ///
        ///三、党小组讨论并提出可否转正的意见
        ///
        ///四、党支部召开支委会审查并提出意见
        ///
        ///五、党支部召开党员大会讨论预备党员转正
        ///
        ///（1）、预备党员提出转正申请，汇报预备期内的思想和工作情况；
        ///
        ///（2）、党小组发表意见；
        ///
        ///（3）、支委会发表意见；
        ///
        ///（4）、大会讨论；
        ///
        ///（5）、党员表决，党支部作出决议。上报党委。
        ///
        ///六、党委召开党委会审批
        ///
        ///七、党委组织部门填写审批意见
        ///
        ///（1）、对延长预备期的党员，在填写时应注明延长预备期的期限（从预备期期满之日算起），交党委书记签名加盖党委印章；
        ///
        ///（2）、将材料及时归档。
        ///
        ///八、党委组织部门通知党支部
        ///
        ///九、党支部负责人与申请转正的预备党员谈话
        /// 的本地化字符串。
        /// </summary>
        internal static string 转正 {
            get {
                return ResourceManager.GetString("转正", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一、申请人、介绍人填写《入党志愿书》
        ///
        ///       党支部应向申请人解释志愿书中的各项内容。填好后，由支部审阅。
        ///
        ///二、党支部召开接收预备党员的党员大会
        ///
        ///（1）、申请人读《入党志愿书》；
        ///
        ///（2）、介绍人发表意见；
        ///
        ///（3）、支委会发表意见；
        ///
        ///（4）、大会讨论；
        ///
        ///（5）、党员表决；
        ///
        ///（6）、作出决议。
        ///
        ///三、党支部填写“党支部决议”并报党委
        ///
        ///       填写支部决议应注明应到和实到正式党员、预备党员数，同意和不同意的人数，通过决议的日期，并由支部书记签名盖章，报党委。
        ///
        ///四、党委指派专人与发展对象谈话
        ///
        ///       谈话前要认真审阅《入党志愿书》及有关资料，谈话中要着重了解申请人对党的认识、入党动机和现实表现；谈话后认真负责地填写谈话情况和谈话人的意见。
        ///
        ///五、党委召开党委会审批
        ///
        ///       党委对党支部上报的接收预备党员的决议，应在三个月内审批，如遇特殊情况可以适当延长审批时间，但不得超过六个月。
        ///
        ///六、党委组织部门填写审批意见
        ///
        ///       对接收为预备党员的，应注明预备期起止的具体时间，（从支部大会通过之日算起），并交 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 预备党员 {
            get {
                return ResourceManager.GetString("预备党员", resourceCulture);
            }
        }
    }
}
